const types = {
    UPDATE_CURRENT_USER_MESSAGES: '[SAGS/AUTH]/UPDATE_CURRENT_USER_MESSAGES',
    UPDATE_CURRENT_USER: '[SAGS/AUTH]/UPDATE_CURRENT_USER',
    CLEAR_CURRENT_USER: '[SAGS/AUTH]/CLEAR_CURRENT_USER',
    SEND_PHONE_LOGIN: '[SAGS/AUTH]/SEND_PHONE_LOGIN',
    SEND_CODE_LOGIN: '[SAGS/AUTH]/SEND_CODE_LOGIN',
    SET_CONTACT: '[SAGS/AUTH]/SET_CONTACT',

    LOGIN: '[SAGS/AUTH]/LOGIN',
    LOGOUT: '[SAGS/AUTH]/LOGOUT',
    SET_AUTH_DATA: '[SAGS/AUTH]/SET_AUTH_DATA',
    CLEAR_AUTH_DATA: '[SAGS/AUTH]/CLEAR_AUTH_DATA',
    RECONNECT_AUTH_DATA: '[SAGS/AUTH]/RECONNECT_AUTH_DATA',
    CHECK_AUTH_DATA: '[SAGS/AUTH]/CHECK_AUTH_DATA',

    GET_ALL_CATEGORY: '[SAGS/CATEGORY]/GET_ALL_CATEGORY',
    SET_CATEGORY: '[SAGS/CATEGORY]/SET_CATEGORY',
    SET_ACTUAL_CATEGORY: '[SAGS/CATEGORY]/SET_ACTUAL_CATEGORY',
    CLEAR_CATEGORY: '[SAGS/CATEGORY]/CLEAR_CATEGORY',

    GET_CLIENT: '[SAGS/CLIENT]/GET_CLIENT',
    SET_CLIENT: '[SAGS/CLIENT]/SET_CLIENT',

    GET_CART: '[SAGS/CART]/GET_CART',
    SET_CART: '[SAGS/CART]/SET_CART',
    ADD_CART: '[SAGS/CART]/ADD_CART',
    SET_NEW_ITEM_CART: '[SAGS/ITEM]/SET_NEW_ITEM_CART',
    UPDATE_CART: '[SAGS/CART]/UPDATE_CART',
    DELETE_CART: '[SAGS/CART]/DELETE_CART',
    CLEAR_CART: '[SAGS/CART]/CLEAR_CART',

    GET_ITEM_ID: '[SAGS/ITEM]/GET_ITEM_ID',
    GET_ITEMS_CATEGORY_ID: '[SAGS/ITEM]/GET_ITEMS_CATEGORY_ID',
    GET_ITEMS_ALL: '[SAGS/ITEM]/GET_ITEMS_ALL',
    SET_ITEMS: '[SAGS/ITEM]/SET_ITEMS',
    SET_PAGE: '[SAGS/ITEM]/SET_PAGE',
    SET_ITEM: '[SAGS/ITEM]/SET_ITEM',
    CLEAR_ITEMS: '[SAGS/ITEM]/CLEAR_ITEMS',
};

export default types;
